robot:
  pinocchio_config:
    urdf_path: "/home/angie/Project/curobo/src/curobo/content/assets/robot/ur_description/ur5e.urdf" # Adjust this path to your own
    robex: null
  curobo_config:
    robot_cfg:
        kinematics:
            usd_path: "robot/ur_description/ur5e.usd"
            usd_robot_root: "/robot"
            isaac_usd_path: ""
            usd_flip_joints: {}
            usd_flip_joint_limits: []

            urdf_path: "robot/ur_description/ur5e.urdf"
            asset_root_path: "robot/ur_description"

            base_link: "base_link"
            ee_link: "tool0"
            link_names: ['shoulder_link', 'upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link', 'wrist_3_link']
            lock_joints: null
            extra_links: null


            collision_link_names: null # List[str]
            collision_spheres: null #
            collision_sphere_buffer: 0.005
            extra_collision_spheres: {}
            self_collision_ignore: null # Dict[str, List[str]]
            self_collision_buffer: null # Dict[str, float]

            use_global_cumul: True
            mesh_link_names: ['shoulder_link', 'upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link', 'wrist_3_link']  # List[str]

            cspace:
                joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
                retract_config:  [-1.57, -2.2, 1.9, -1.383, -1.57, 0.00]
                null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
                cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
                max_jerk: 500.0
                max_acceleration: 15.0



env:
  - type: 'Sphere'
    dim: 0.2
    pose: [0.5, 0.5, 0.5, 1, 0, 0, 0]

  - type: 'Sphere'
    dim: 0.05
    pose: [0.2, 0.0, -0.1, 1, 0, 0, 0]
