robot:
  pinocchio_config:
    urdf_path: "/home/angie/Projects/curobo/src/curobo/content/assets/robot/ur_description/ur5e.urdf"
    robex: "ur5"
  curobo_config: "ur5e.yml"



env:
  - type: 'Sphere'
    dim: 0.1
    pose: [0.4, 0, -0.4, 1, 0, 0, 0]

  - type: 'Sphere'
    dim: 0.1
    pose: [0.0, 0.0, -0.5, 1, 0, 0, 0]
