robot:
  pinocchio_config:
    urdf_path: null
    robex: "ur10"
  curobo_config: "ur10e.yml"



env:
  - type: 'Sphere'
    dim: 0.2
    pose: [0.5, 0.5, 0.5, 1, 0, 0, 0]

  - type: 'Sphere'
    dim: 0.1
    pose: [0.5, 0.5, 0.5, 1, 0, 0, 0]
