robot_cfg:
    kinematics:
        usd_path: "robot/ur_description/ur5e.usd"
        usd_robot_root: "/robot"
        isaac_usd_path: ""
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "robot/ur_description/ur5e.urdf"
        asset_root_path: "robot/ur_description"

        base_link: "base_link"
        ee_link: "tool0"
        link_names: null
        lock_joints: null
        extra_links: null


        collision_link_names: null # List[str]
        collision_spheres: null #
        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        self_collision_ignore: null # Dict[str, List[str]]
        self_collision_buffer: null # Dict[str, float]

        use_global_cumul: True
        mesh_link_names: null # List[str]

        cspace:
            joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
            retract_config:  [-1.57, -2.2, 1.9, -1.383, -1.57, 0.00]
            null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            max_jerk: 500.0
            max_acceleration: 15.0



env:
  - type: 'Sphere'
    dim: 0.1
    pose: [0.5, 0.5, 0.5]

  - type: 'Sphere'
    dim: 0.1
    pose: [0.5, 0.5, 0.5]

  - type: 'Mesh'
    file_path: "scene/nvblox/srl_ur10_bins.obj"
    pose: [1.5, 0.080, 1.6, 0.043, -0.471, 0.284, 0.834]